site_name: Tileon
site_url: https://bluemoon-o2.github.io/tileon
repo_url: https://github.com/bluemoon-o2/tileon

theme:
  name: material
  logo: assets/tileon-logo.png
  favicon: assets/tileon-logo.png
  language: en

  features:
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.prune
    - navigation.top

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            "Getting Started": "快速开始"
            "Programming Guide": "编程指南"
            "Python API": "Python API"
            "Contributing": "贡献指南"
            "License": "许可协议"

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            group_by_category: false
            signature_crossrefs: true
            show_signature: true
            docstring_section_style: list
            show_root_heading: true
            heading_level: 3
            preload_modules:
              - typing
              - typing_extensions

watch:
  - python/tileon
  - README.md
  - docs

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Tutorials:
      - Overview: getting-started/tutorials/index.md
      - Vector Add: getting-started/tutorials/vector-add.md
      - Matrix Multiplication: getting-started/tutorials/matrix-multiplication.md
  - Programming Guide:
    - Introduction: programming-guide/chapter-1/introduction.md
    - Basics: programming-guide/chapter-2/basics.md
    - Advanced: programming-guide/chapter-3/advanced.md
  - Python API:
    - tileon: python-api/tileon.md
    - tileon.language: python-api/tileon.language.md
    - tileon.language.math: python-api/tileon.language.math.md
    - tileon.language.random: python-api/tileon.language.random.md
    - tileon.testing: python-api/tileon.testing.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: bluemoon-o2
      repo: tileon
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables

copyright: >
  Copyright &copy; 2026 Tileon Team -
  <a href="#__consent">Change cookie settings</a>
